-- AlterTable
ALTER TABLE "personal_infos" ADD COLUMN     "photoOffsetX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "photoOffsetY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "photoZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
